package lootboxes.LBContent.LootTables;

import necesse.inventory.lootTable.LootItemInterface;
import necesse.inventory.lootTable.LootTable;
import necesse.inventory.lootTable.lootItem.LootItem;
import necesse.inventory.lootTable.lootItem.OneOfLootItems;

public class RandomFoodBagLootTable extends LootTable {
    public static final OneOfLootItems food1 = new OneOfLootItems(LootItem.between("blackcoffee", 1, 3),
            new LootItemInterface[]{LootItem.between("bread", 1, 3),
                    LootItem.between("candyapple", 1, 3),
                    LootItem.between("candycane", 1, 3),
                    LootItem.between("cappuccino", 1, 3),
                    LootItem.between("cheese", 1, 3),
                    LootItem.between("chickendrumstick", 1, 3),
                    LootItem.between("cookies", 1, 3),
                    LootItem.between("donut", 1, 3),
                    LootItem.between("friedegg", 1, 3),
                    LootItem.between("hardboiledegg", 1, 3),
                    LootItem.between("popcorn", 1, 3),
                    LootItem.between("raspberryjuice", 1, 3),
                    LootItem.between("roastedduckbreast", 1, 3),
                    LootItem.between("roastedfish", 1, 3),
                    LootItem.between("roastedfrogleg", 1, 3),
                    LootItem.between("roastedpork", 1, 3),
                    LootItem.between("roastedrabbitleg", 1, 3),
                    LootItem.between("scrambledeggs", 1, 3),
                    LootItem.between("steak", 1, 3),
                    LootItem.between("bananapudding", 1, 2),
                    LootItem.between("beefgoulash", 1, 2),
                    LootItem.between("blackberryicecream", 1, 2),
                    LootItem.between("blueberrycake", 1, 2),
                    LootItem.between("cheeseburger", 1, 2),
                    LootItem.between("chickencutletdish", 1, 2),
                    LootItem.between("deepfriedchicken", 1, 2),
                    LootItem.between("dessertpancakes", 1, 2),
                    LootItem.between("eggplantparmesan", 1, 2),
                    LootItem.between("fishtaco", 1, 2),
                    LootItem.between("fishandchips", 1, 2),
                    LootItem.between("freshpotatosalad", 1, 2),
                    LootItem.between("friedpork", 1, 2),
                    LootItem.between("fruitsmoothie", 1, 2),
                    LootItem.between("hotdog", 1, 2),
                    LootItem.between("juniorburger", 1, 2),
                    LootItem.between("lemontart", 1, 2),
                    LootItem.between("meatballs", 1, 2),
                    LootItem.between("minersstew", 1, 2),
                    LootItem.between("nachos", 1, 2),
                    LootItem.between("omelette", 1, 2),
                    LootItem.between("parisiansteak", 1, 2),
                    LootItem.between("porktenderloin", 1, 2),
                    LootItem.between("pumpkinpie", 1, 2),
                    LootItem.between("raspberryjam", 1, 2),
                    LootItem.between("raspberrymousse", 1, 2),
                    LootItem.between("raspberrypie", 1, 2),
                    LootItem.between("ricepudding", 1, 2),
                    LootItem.between("shishkebab", 1, 2),
                    LootItem.between("smokedfillet", 1, 2),
                    LootItem.between("spaghettibolognese", 1, 2),
                    LootItem.between("strawberrypie", 1, 2),
                    LootItem.between("sushirolls", 1, 2),
                    LootItem.between("sweetlemonade", 1, 2),
                    LootItem.between("tropicalstew", 1, 2),
                    LootItem.between("wildsalad", 1, 2),
            });

    public static final OneOfLootItems food2 = new OneOfLootItems(LootItem.between("blackcoffee", 1, 3),
            new LootItemInterface[]{LootItem.between("bread", 1, 3),
                    LootItem.between("candyapple", 1, 3),
                    LootItem.between("candycane", 1, 3),
                    LootItem.between("cappuccino", 1, 3),
                    LootItem.between("cheese", 1, 3),
                    LootItem.between("chickendrumstick", 1, 3),
                    LootItem.between("cookies", 1, 3),
                    LootItem.between("donut", 1, 3),
                    LootItem.between("friedegg", 1, 3),
                    LootItem.between("hardboiledegg", 1, 3),
                    LootItem.between("popcorn", 1, 3),
                    LootItem.between("raspberryjuice", 1, 3),
                    LootItem.between("roastedduckbreast", 1, 3),
                    LootItem.between("roastedfish", 1, 3),
                    LootItem.between("roastedfrogleg", 1, 3),
                    LootItem.between("roastedpork", 1, 3),
                    LootItem.between("roastedrabbitleg", 1, 3),
                    LootItem.between("scrambledeggs", 1, 3),
                    LootItem.between("steak", 1, 3),
                    LootItem.between("bananapudding", 1, 2),
                    LootItem.between("beefgoulash", 1, 2),
                    LootItem.between("blackberryicecream", 1, 2),
                    LootItem.between("blueberrycake", 1, 2),
                    LootItem.between("cheeseburger", 1, 2),
                    LootItem.between("chickencutletdish", 1, 2),
                    LootItem.between("deepfriedchicken", 1, 2),
                    LootItem.between("dessertpancakes", 1, 2),
                    LootItem.between("eggplantparmesan", 1, 2),
                    LootItem.between("fishtaco", 1, 2),
                    LootItem.between("fishandchips", 1, 2),
                    LootItem.between("freshpotatosalad", 1, 2),
                    LootItem.between("friedpork", 1, 2),
                    LootItem.between("fruitsmoothie", 1, 2),
                    LootItem.between("hotdog", 1, 2),
                    LootItem.between("juniorburger", 1, 2),
                    LootItem.between("lemontart", 1, 2),
                    LootItem.between("meatballs", 1, 2),
                    LootItem.between("minersstew", 1, 2),
                    LootItem.between("nachos", 1, 2),
                    LootItem.between("omelette", 1, 2),
                    LootItem.between("parisiansteak", 1, 2),
                    LootItem.between("porktenderloin", 1, 2),
                    LootItem.between("pumpkinpie", 1, 2),
                    LootItem.between("raspberryjam", 1, 2),
                    LootItem.between("raspberrymousse", 1, 2),
                    LootItem.between("raspberrypie", 1, 2),
                    LootItem.between("ricepudding", 1, 2),
                    LootItem.between("shishkebab", 1, 2),
                    LootItem.between("smokedfillet", 1, 2),
                    LootItem.between("spaghettibolognese", 1, 2),
                    LootItem.between("strawberrypie", 1, 2),
                    LootItem.between("sushirolls", 1, 2),
                    LootItem.between("sweetlemonade", 1, 2),
                    LootItem.between("tropicalstew", 1, 2),
                    LootItem.between("wildsalad", 1, 2),
            });
    public static final OneOfLootItems food3 = new OneOfLootItems(LootItem.between("blackcoffee", 1, 3),
            new LootItemInterface[]{LootItem.between("bread", 1, 3),
                    LootItem.between("candyapple", 1, 3),
                    LootItem.between("candycane", 1, 3),
                    LootItem.between("cappuccino", 1, 3),
                    LootItem.between("cheese", 1, 3),
                    LootItem.between("chickendrumstick", 1, 3),
                    LootItem.between("cookies", 1, 3),
                    LootItem.between("donut", 1, 3),
                    LootItem.between("friedegg", 1, 3),
                    LootItem.between("hardboiledegg", 1, 3),
                    LootItem.between("popcorn", 1, 3),
                    LootItem.between("raspberryjuice", 1, 3),
                    LootItem.between("roastedduckbreast", 1, 3),
                    LootItem.between("roastedfish", 1, 3),
                    LootItem.between("roastedfrogleg", 1, 3),
                    LootItem.between("roastedpork", 1, 3),
                    LootItem.between("roastedrabbitleg", 1, 3),
                    LootItem.between("scrambledeggs", 1, 3),
                    LootItem.between("steak", 1, 3),
                    LootItem.between("bananapudding", 1, 2),
                    LootItem.between("beefgoulash", 1, 2),
                    LootItem.between("blackberryicecream", 1, 2),
                    LootItem.between("blueberrycake", 1, 2),
                    LootItem.between("cheeseburger", 1, 2),
                    LootItem.between("chickencutletdish", 1, 2),
                    LootItem.between("deepfriedchicken", 1, 2),
                    LootItem.between("dessertpancakes", 1, 2),
                    LootItem.between("eggplantparmesan", 1, 2),
                    LootItem.between("fishtaco", 1, 2),
                    LootItem.between("fishandchips", 1, 2),
                    LootItem.between("freshpotatosalad", 1, 2),
                    LootItem.between("friedpork", 1, 2),
                    LootItem.between("fruitsmoothie", 1, 2),
                    LootItem.between("hotdog", 1, 2),
                    LootItem.between("juniorburger", 1, 2),
                    LootItem.between("lemontart", 1, 2),
                    LootItem.between("meatballs", 1, 2),
                    LootItem.between("minersstew", 1, 2),
                    LootItem.between("nachos", 1, 2),
                    LootItem.between("omelette", 1, 2),
                    LootItem.between("parisiansteak", 1, 2),
                    LootItem.between("porktenderloin", 1, 2),
                    LootItem.between("pumpkinpie", 1, 2),
                    LootItem.between("raspberryjam", 1, 2),
                    LootItem.between("raspberrymousse", 1, 2),
                    LootItem.between("raspberrypie", 1, 2),
                    LootItem.between("ricepudding", 1, 2),
                    LootItem.between("shishkebab", 1, 2),
                    LootItem.between("smokedfillet", 1, 2),
                    LootItem.between("spaghettibolognese", 1, 2),
                    LootItem.between("strawberrypie", 1, 2),
                    LootItem.between("sushirolls", 1, 2),
                    LootItem.between("sweetlemonade", 1, 2),
                    LootItem.between("tropicalstew", 1, 2),
                    LootItem.between("wildsalad", 1, 2),
            });
    public static final RandomFoodBagLootTable instance = new RandomFoodBagLootTable();

    private RandomFoodBagLootTable() {
        super(new LootItemInterface[]{food1, food2, food3});
    }

}